name: kind_cash_pro
description: Kind Cash Pro Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  http: ^0.13.4
  get: ^4.6.1
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.1.0
  device_preview: ^1.0.0
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0

flutter:

  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
